kind: Namespace
apiVersion: v1
metadata: 
  name: web-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryhfd4279.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
          - name: TRIPS_API_ENDPOINT
            value: "http://trips-svc"
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile-svc"

---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-svc
  namespace: web-dev
  labels:
    app: tripviewer
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: tripviewer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: tripviewer
  namespace: web-dev
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: tripviewer-svc
            servicePort: 80
          path: /
