kind: Namespace
apiVersion: v1
metadata: 
  name: api-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: api-dev
  labels:
    app: user-java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryhfd4279.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "db-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-svc
  namespace: api-dev
  labels:
    app: user-java
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: user-java
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: user-java
  namespace: api-dev
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: user-java-svc
            servicePort: 80
          path: /api/user-java
