kind: Namespace
apiVersion: v1
metadata: 
  name: api-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api-dev
  labels:
    app: userprofile-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
     containers:
      - name: userprofile
        image: registryhfd4279.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        # env:
        #   - name: SQL_SERVER
        #     valueFrom:
        #       secretKeyRef:
        #         name: db-secret
        #         key: SQL_SERVER
        #   - name: SQL_DBNAME
        #     valueFrom:
        #       secretKeyRef:
        #         name: db-secret
        #         key: SQL_DBNAME
        #   - name: SQL_USER
        #     valueFrom:
        #       secretKeyRef:
        #         name: db-secret
        #         key: SQL_USER
        #   - name: SQL_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: db-secret
        #         key: SQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-svc
  namespace: api-dev
  labels:
    app: userprofile
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: userprofile
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: userprofile
  namespace: api-dev
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: userprofile-svc
            servicePort: 80
          path: /api/user