apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: web
  name: web-dev-rolebinding
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: {{WEBDEV_GROUP_ID}}
  apiGroup: rbac.authorization.k8s.io
  namespace: web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: api
  name: web-dev-rolebinding
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: {{WEBDEV_GROUP_ID}}
  apiGroup: rbac.authorization.k8s.io
  namespace: api
