apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: web-dev
  name: web-dev-group-rolebinding
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: 4db1d396-e2f4-4095-b310-17b65b5ac7d6
  apiGroup: rbac.authorization.k8s.io
  namespace: web-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: api-dev
  name: web-dev-group-rolebinding
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: 4db1d396-e2f4-4095-b310-17b65b5ac7d6
  apiGroup: rbac.authorization.k8s.io
  namespace: api-dev
